version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
     - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
     - '5432:5432'

  web:
    build: .
    stdin_open: true
    tty: true
    depends_on:
     - 'db'
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    volumes:
     - .:/home/app/web
     - gems:/app-gems
    ports:
     - '3000:3000'

volumes:
  db:
  gems: 